require:
 - rubocop-performance
 - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

Style/WordArray:
  EnforcedStyle: brackets

Style/NumericLiterals:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

RSpec/ExampleLength:
  Enabled: false

Metrics:
  Enabled: false

Style/Documentation:
  Enabled: false